apiVersion: v1
data:
  config.json: |-
    {
      // Publicly accessible URL to web app (e.g., what you type into your browser).
      "appURL": "https://${INGRESS_URL}",

      // The authentication provider to use for identifying and signing in users. Only one entry is supported.
      //
      // The builtin auth provider with signup disallowed (shown below) means that after the initial site admin signs in, all other users must be invited.
      //
      // Other providers are documented here:
      // https://about.sourcegraph.com/docs/config/site#authproviders-array
      "auth.providers": [{"type": "builtin", "allowSignup": false}],
      "github": [
        {
          "token": "${GH_ACCESS_TOKEN}",
          "url": "https://github.com"
        }
      ]
    }
kind: ConfigMap
metadata:
  labels:
    deploy: sourcegraph
  name: config-file
